name: Deploy to HF Space
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "deploy@github.com"
          git config user.name "GitHub Actions"
          git remote add hf https://Sathishj26:$HF_TOKEN@huggingface.co/spaces/Sathishj26/MarketTerminal
          git push hf main --force
